"""Fix course_created_by_fkey

Revision ID: b68bbb26c1b0
Revises: a2802fa4ee77
Create Date: 2023-01-27 19:12:42.754183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68bbb26c1b0'
down_revision = 'a2802fa4ee77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_created_by_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['created_by'], ['id_'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_created_by_fkey', 'course', 'profile', ['created_by'], ['id_'])
    # ### end Alembic commands ###
