"""Move is_active to user

Revision ID: f2554d34c8c4
Revises: ff8762ff8288
Create Date: 2023-01-25 21:13:30.376508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2554d34c8c4'
down_revision = 'ff8762ff8288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_completed_content_blocks_id', table_name='completed_content_blocks')
    op.create_index(op.f('ix_completed_content_blocks_id_'), 'completed_content_blocks', ['id_'], unique=False)
    op.drop_index('ix_content_blocks_id', table_name='content_blocks')
    op.create_index(op.f('ix_content_blocks_id_'), 'content_blocks', ['id_'], unique=False)
    op.drop_index('ix_courses_id', table_name='courses')
    op.create_index(op.f('ix_courses_id_'), 'courses', ['id_'], unique=False)
    op.drop_index('ix_profiles_id', table_name='profiles')
    op.create_index(op.f('ix_profiles_id_'), 'profiles', ['id_'], unique=False)
    op.drop_column('profiles', 'is_active')
    op.drop_index('ix_sections_id', table_name='sections')
    op.create_index(op.f('ix_sections_id_'), 'sections', ['id_'], unique=False)
    op.drop_index('ix_student_courses_id', table_name='student_courses')
    op.create_index(op.f('ix_student_courses_id_'), 'student_courses', ['id_'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id_'), 'users', ['id_'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id_'], unique=False)
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_student_courses_id_'), table_name='student_courses')
    op.create_index('ix_student_courses_id', 'student_courses', ['id_'], unique=False)
    op.drop_index(op.f('ix_sections_id_'), table_name='sections')
    op.create_index('ix_sections_id', 'sections', ['id_'], unique=False)
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_profiles_id_'), table_name='profiles')
    op.create_index('ix_profiles_id', 'profiles', ['id_'], unique=False)
    op.drop_index(op.f('ix_courses_id_'), table_name='courses')
    op.create_index('ix_courses_id', 'courses', ['id_'], unique=False)
    op.drop_index(op.f('ix_content_blocks_id_'), table_name='content_blocks')
    op.create_index('ix_content_blocks_id', 'content_blocks', ['id_'], unique=False)
    op.drop_index(op.f('ix_completed_content_blocks_id_'), table_name='completed_content_blocks')
    op.create_index('ix_completed_content_blocks_id', 'completed_content_blocks', ['id_'], unique=False)
    # ### end Alembic commands ###
